/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _ASM_POWERPC_CRASH_RESERVE_H
#define _ASM_POWERPC_CRASH_RESERVE_H

/* crash kernel regions are Page size agliged */
#define CRASH_ALIGN		PAGE_SIZE

#define DEFAULT_CRASH_KERNEL_LOW_SIZE SZ_128M

#define CRASH_ADDR_LOW_MAX	SZ_512M + SZ_256M + SZ_128M + SZ_64M + SZ_16M + SZ_1M
#define CRASH_ADDR_HIGH_MAX	CRASH_ADDR_LOW_MAX + SZ_4G


#endif /* _ASM_POWERPC_CRASH_RESERVE_H */
